version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      safe-dependencies:
        update-types: ['minor', 'patch']
      major-dependencies:
        update-types: ['major']
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
