packages:
  - 'packages/*'
allowBuilds:
  '@firebase/util': false
  '@vaadin/vaadin-usage-statistics': false
  esbuild: true
  msw: true
  protobufjs: false
  re2: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@ugrc/*'
  - uuid@11.1.1
  - qs@6.15.2
minimumReleaseAgeStrict: true
