name: Release Events

on:
  release:
    types: [published]

permissions:
  id-token: write
  deployments: write

jobs:
  deploy:
    name: Create and publish package
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: read
      id-token: write
    steps:
      - name: 🏷️ Extract package name from tag
        uses: MeilCli/regex-match@v2
        id: folder
        with:
          regex_pattern: '.*(?=-v*)'
          search_string: ${{ github.ref_name }}

      - name: 🛑 Fail if no package name found
        run: exit 1
        if: ${{ !steps.folder.outputs.matched }}

      - name: ⬇️ Set up code
        uses: actions/checkout@v6
        with:
          show-progress: false

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          check-latest: true
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: 📥 Download dependencies
        run: pnpm install --frozen-lockfile

      - name: 🏗 Run build script
        run: pnpm build

      - name: 🚢 Publish package
        run: pnpm --filter @ugrc/${{ steps.folder.outputs.matched_first }} publish --access public --no-git-checks

  deploy-storybook:
    name: 📚 Deploy documentation
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: prod
    concurrency:
      group: ${{ github.workflow }}-storybook
      cancel-in-progress: true

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6
        with:
          show-progress: false

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 🚀 Deploy
        uses: agrc/firebase-website-deploy-composite-action@v2
        with:
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project-id: ${{ secrets.PROJECT_ID }}
          prebuild-command: pnpm --filter @ugrc/utilities build && pnpm build
          build-command: pnpm build:storybook
        env:
          VITE_QUAD_WORD: ${{ secrets.DISCOVER_QUAD_WORD }}
